### ISSUE TITLE
Traceback error when running python app.py

### ISSUE THREAD

**Issue by fstricker** [carpiero/DataTown#1]
Cannot get the app to run on Ubuntu server (20.04) nor on macOS Big Sur (11.6.5), and would appreciate some help. When `python app.py`, I get:

`Traceback (most recent call last):
  File "app.py", line 5, in <module>
    import dash
  File "/Users/boludo/opt/anaconda3/envs/DTenv/lib/python3.7/site-packages/dash/__init__.py", line 1, in <module>
    from .dash import Dash, no_update  # noqa: F401
  File "/Users/boludo/opt/anaconda3/envs/DTenv/lib/python3.7/site-packages/dash/dash.py", line 19, in <module>
    from werkzeug.debug.tbtools import get_current_traceback
ImportError: cannot import name 'get_current_traceback' from 'werkzeug.debug.tbtools' (/Users/boludo/opt/anaconda3/envs/DTenv/lib/python3.7/site-packages/werkzeug/debug/tbtools.py)`

**Reproduction/my steps involved:**

- `conda create -n DTenv python=3.7.3`
- `conda activate DTenv`
- `git clone https://github.com/carpiero/DataTown.git`
- `cd DataTown`
- `pip install -r requirements.txt`

**My trouble shooting:**

The dash:werkzeug conflict seems to be what it described here (https://github.com/plotly/dash/issues/1992). There appear to be two fix approaches:

- downgrading werkzeug
- updating dash.py

**downgrading werkzeug `pip install Werkzeug==2.0.0`):**
First I get a dependency error w/ `flask 2.2.2 requires Werkzeug>=2.2.2`. When running `python app.py` I get: 

`Traceback (most recent call last):
  File "app.py", line 5, in <module>
    import dash
  File "/Users/boludo/opt/anaconda3/envs/finalDataTown/lib/python3.7/site-packages/dash/__init__.py", line 1, in <module>
    from .dash import Dash, no_update  # noqa: F401
  File "/Users/boludo/opt/anaconda3/envs/finalDataTown/lib/python3.7/site-packages/dash/dash.py", line 17, in <module>
    import flask
  File "/Users/boludo/opt/anaconda3/envs/finalDataTown/lib/python3.7/site-packages/flask/__init__.py", line 4, in <module>
    from . import json as json
  File "/Users/boludo/opt/anaconda3/envs/finalDataTown/lib/python3.7/site-packages/flask/json/__init__.py", line 8, in <module>
    from ..globals import current_app
  File "/Users/boludo/opt/anaconda3/envs/finalDataTown/lib/python3.7/site-packages/flask/globals.py", line 57, in <module>
    _cv_app, unbound_message=_no_app_msg
TypeError: __init__() got an unexpected keyword argument 'unbound_message'`

**updating dash.py:**
After changing `get_current_traceback` to `DebugTraceback`, and running the app, I still get:

`Traceback (most recent call last):
  File "app.py", line 28, in <module>
    app = dash.Dash(__name__, meta_tags=[{"name": "viewport", "content": "width=device-width"}],title='DataTown',update_title='Cargando...')
  File "/Users/boludo/opt/anaconda3/envs/finalDataTown/lib/python3.7/site-packages/dash/dash.py", line 257, in __init__
    _validate.check_obsolete(obsolete)
  File "/Users/boludo/opt/anaconda3/envs/finalDataTown/lib/python3.7/site-packages/dash/_validate.py", line 281, in check_obsolete
    raise TypeError("Dash() got an unexpected keyword argument '" + key + "'")`

**Comment by fstricker** [comment]
Perhaps I'm doing something wrong, but to me it seems as if you need to change 2 things in order to get the app running: 
1) find/replace `get_current_traceback`with `DebugTraceback` in your virtual environment's dash.py
2) omit the `title`and `update_date` parameters within `app = dash.Dash(...)` of your app.py

Not doing so throws the following for me:
`Traceback (most recent call last):
  File "app.py", line 30, in <module>
    app = dash.Dash(__name__, meta_tags=[{"name": "viewport", "content": "width=device-width"}],title='DataTown',update_title='Cargando...')
  File "/Users/boludo/opt/anaconda3/envs/DTenv/lib/python3.7/site-packages/dash/dash.py", line 258, in __init__
    _validate.check_obsolete(obsolete)
  File "/Users/boludo/opt/anaconda3/envs/DTenv/lib/python3.7/site-packages/dash/_validate.py", line 281, in check_obsolete
    raise TypeError("Dash() got an unexpected keyword argument '" + key + "'")
TypeError: Dash() got an unexpected keyword argument 'title'
`
